
[theme]
name = "native"

[icons]
name = "awesome"

[[block]]
block = "pacman"
interval = 600
format = "{pacman} updates available"
format_singular = "{pacman} update available"
format_up_to_date = ""
critical_updates_regex = "(linux |linux-lts|linux-zen)"

[[block]]
block = "temperature"
collapsed = false
interval = 10
format = "{max}°"
chip = "coretemp-isa-0000"

[[block]]
block = "speedtest"
bytes = true
interval = 1800

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{Mup}%"
format_swap = "{SUp}%"

[[block]]
block = "cpu"
interval = 1


[[block]]
block = "bluetooth"
mac = "E8:07:BF:30:FE:34"
label = ""

[[block]]
block = "sound"

[[block]]
block = "time"
interval = 60
format = "%a %d/%m %R"

#[[block]]
#block = "battery"
#interval = 10
#format = "{percentage}% {time}"
